linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  LeadingZero:
    enabled: true
    style: 'include_zero' # or 'exclude_zero'

  PropertySortOrder:
    enabled: false

  VendorPrefix:
    enabled: false
