language: node_js
node_js:
  - "0.12"

script: grunt

before_install:
  - npm install -g grunt-cli
  - gem install scss-lint
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start